version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_marbleyou:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: odigvard/marbleyou
    env_file: .env
    volumes:
      - static_volume:/static_marbleyou
      - media_marbleyou:/media
    depends_on:
      - db

  gateway:
    image: odigvard/marbleyou_gateway
    env_file: .env
    volumes:
      - static_volume:/staticfiles
      - media_marbleyou:/media_marbleyou
    ports:
      - 8000:80
    depends_on:
      - backend