# Generated by Django 4.2.6 on 2023-10-22 12:50

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Обработана')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU', verbose_name='Телефон')),
                ('product', models.CharField(blank=True, default='Изделие не указано', max_length=256, null=True, verbose_name='Изделие')),
                ('length', models.IntegerField(validators=[django.core.validators.MinValueValidator(15, message='Указывайте размеры в сантиметрах')], verbose_name='Длина')),
                ('width', models.IntegerField(validators=[django.core.validators.MinValueValidator(15, message='Указывайте размеры в сантиметрах')], verbose_name='Ширина')),
                ('thickness', models.IntegerField(choices=[(10, '1 см'), (20, '2 см'), (30, '3 см'), (40, '4 см'), (50, '5 см')], default=30, verbose_name='Толщина')),
                ('cut', models.IntegerField(blank=True, null=True, verbose_name='Рез камня')),
                ('edge', models.IntegerField(blank=True, null=True, verbose_name='Полировка кромки')),
                ('array', models.IntegerField(blank=True, null=True, verbose_name='Площадь материала')),
                ('hob', models.BooleanField(default=False, verbose_name='Вырез под варочную панель')),
                ('sink', models.BooleanField(default=False, verbose_name='Вырез под раковину')),
                ('tap', models.BooleanField(default=False, verbose_name='Отверстие под кран')),
                ('riser_array', models.IntegerField(blank=True, null=True, verbose_name='Площадь материала подступенка')),
                ('dropper', models.IntegerField(blank=True, null=True, verbose_name='Капельник')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('final_price_production', models.IntegerField(blank=True, null=True, verbose_name='Общая стоимость производства')),
                ('final_price', models.IntegerField(blank=True, null=True, verbose_name='Итоговая стоимость')),
                ('general_info', models.TextField(blank=True, null=True, verbose_name='Общая информация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'расчет',
                'verbose_name_plural': 'Заявка на расчет',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Ваш вопрос')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'Форма обратной связи',
            },
        ),
        migrations.CreateModel(
            name='WorkPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cut', models.IntegerField(default=700, verbose_name='Рез камня')),
                ('edge', models.IntegerField(default=1300, verbose_name='Кромка')),
                ('average', models.IntegerField(default=13000, verbose_name='Средняя стоимость материала')),
                ('hob', models.IntegerField(default=3200, verbose_name='Вырез под плиту')),
                ('sink', models.IntegerField(default=4000, verbose_name='Вырез под раковину')),
                ('tap', models.IntegerField(default=1500, verbose_name='Отверстие под кран')),
                ('dropper', models.IntegerField(default=400, verbose_name='Капельник')),
            ],
            options={
                'verbose_name': 'цена производства',
                'verbose_name_plural': 'Цены на производство',
            },
        ),
    ]
