# Generated by Django 4.2.6 on 2023-10-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_feedback_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(blank=True, verbose_name='Комментарий к заказу')),
                ('status', models.CharField(choices=[('Открытый', 'Открытый'), ('В работе', 'В работе'), ('Закрытый', 'Закрытый')], default='Открытый', max_length=20, verbose_name='Статус')),
                ('addition', models.TextField(blank=True, verbose_name='Дополнение к заказу')),
                ('composition', models.TextField(blank=True, verbose_name='Состав заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
