# Generated by Django 3.2.16 on 2023-02-19 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название категории (пример: столешницы, лестницы)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'категория изделий',
                'verbose_name_plural': 'Категории изделий',
            },
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Вид камня (например: гранит)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('slug', models.SlugField(help_text='Идентификатор страницы для URL; разрешены символы латиницы, цифры, дефис и подчёркивание.', max_length=64, unique=True, verbose_name='Идентификатор')),
            ],
            options={
                'verbose_name': 'вид камня',
                'verbose_name_plural': 'Виды камня',
            },
        ),
        migrations.CreateModel(
            name='Stone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Изображение')),
                ('length', models.IntegerField(blank=True, null=True, verbose_name='Длина мм')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Ширина мм')),
                ('thickness', models.IntegerField(blank=True, null=True, verbose_name='Толщина мм')),
                ('slug', models.SlugField(help_text='Идентификатор страницы для URL; разрешены символы латиницы, цифры, дефис и подчёркивание.', max_length=64, unique=True, verbose_name='Идентификатор')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('genus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genus', to='product.genus', verbose_name='Вид камня')),
            ],
            options={
                'verbose_name': 'камень',
                'verbose_name_plural': 'Камень',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Наименование изделия (пример: столешницы из сланца)')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Изображение')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('slug', models.SlugField(help_text='Идентификатор страницы для URL; разрешены символы латиницы, цифры, дефис и подчёркивание.', max_length=64, unique=True, verbose_name='Идентификатор')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='product.category', verbose_name='Категории изделия')),
                ('genus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_genus', to='product.genus', verbose_name='Вид камня')),
            ],
            options={
                'verbose_name': 'изделие',
                'verbose_name_plural': 'Изделия',
            },
        ),
    ]
