# Generated by Django 3.2.16 on 2023-02-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/category', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/product', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='stone',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/stone', verbose_name='Изображение'),
        ),
    ]
