# Generated by Django 4.2.6 on 2023-4-16 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20230922_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='second_description',
            field=models.TextField(blank=True, verbose_name='Второе описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='StoneAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/stone/album')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='stone_album', to='product.stone')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'Альбом камня',
            },
        ),
        migrations.CreateModel(
            name='ProductAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/product/album')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_lbum', to='product.product')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'Альбом изделий в карусель',
            },
        ),
        migrations.CreateModel(
            name='CategoryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/category/album')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_album', to='product.category')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'Альбом для главной страницы',
            },
        ),
    ]
