# Generated by Django 4.2.6 on 2023-5-17 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_second_description_alter_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'Альбом карусели на главной',
            },
        ),
        migrations.CreateModel(
            name='HomePageAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/homepage/album')),
                ('homepage', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='homepage_album', to='product.homepage')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'Альбом главной',
            },
        ),
        migrations.AlterField(
            model_name='productalbum',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_album', to='product.product'),
        ),
        migrations.DeleteModel(
            name='CategoryAlbum',
        ),
    ]
