# Generated by Django 4.2.6 on 2023-5-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_homepage_homepagealbum_alter_productalbum_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Ваш вопрос')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'Форма обратной связи',
            },
        ),
        migrations.RenameField(
            model_name='stonealbum',
            old_name='product',
            new_name='stone',
        ),
    ]
