# Generated by Django 4.2.6 on 2023-10-22 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_stone_second_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalculationData',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
